### ISSUE TITLE
Issue setting up env, cu113

### ISSUE THREAD

**Issue by jdilger** [cliffbb/OEM-Fewshot-Challenge#5]
I had trouble setting up my env following the instructions in the **Usage** section. Specifically, I was getting : `ERROR: Could not find a version that satisfies the requirement torch==1.10.2+cu113`

I solved this by installing the cu112 wheel as is shown in the DIaM [requirements.txt](https://github.com/sinahmr/DIaM/blob/37f38c383246bc323cab7f1b0dca70eee0557eb9/requirements.txt#L1).  Is there a reason why this was removed from the requirements? Happy to make a small PR to add it back in if you want 😄

**Comment by cliffbb** [comment]
@jdilger Thank you for letting me know. Accidentally deleted. I didn't notice it. It's been added.

**Comment by jdilger** [comment]
No problem, happy to contribute!
